### PR TITLE
Update readme and docs

### LINKED ISSUE #17: Add Artifact Evaluation committee to website
List the following reviewers under a new section of the [Climate Informatics 2024 website](https://alan-turing-institute.github.io/climate-informatics-2024-ae):
- James Emberton (ICCS, University of Cambridge)
- James Robinson (Alan Turing Institute)
- Etienne Roesch (University of Reading)
- Bryn Noel Ubald (British Antarctic Survey)
- Alexandra Udaltsova (Open Climate Fix)

### PR DESCRIPTION
**Pull request by acocac**
The PR updates README and intro.md in docs. 

The README includes a Zenodo badge. Both README and intro.md acknowledge the program committee (reviewers).

### CODE REVIEW

**Comment by acocac** [comment]
@rolyp sharing for your revision the PR adding/naming the reviewers in the repo.

**Review by MarionBWeinzierl — APPROVED** [review]
This is a good extension of the README and documentation

**Comment by acocac** [comment]
> This is a good extension of the README and documentation

Thanks @MarionBWeinzierl! I am not sure if we should modify other sections in docs i.e. changing from future to past tense, or leave as they are. We could cross-reference the blogpost once it's live.

**Review by rolyp — APPROVED** [review]
Looks good. Minor tweak: "(The Alan Turing Institute)" rather than "(Alan Turing Institute)" after James Robinson's name.

**Comment by acocac** [comment]
> Looks good. Minor tweak: "(The Alan Turing Institute)" rather than "(Alan Turing Institute)" after James Robinson's name.

Thank you! Fixed.

**Pull request merged**
